[package]
name = "find_peaks"
version = "0.1.0"
edition = "2018"

[lib]
name = "find_peaks"
crate-type = ["cdylib"]

[dependencies]
find_peaks = "0.1.5"
pyo3 = { version = "0.17.2", features = ["extension-module"] }
